name: Update version.txt with commit

on:
  push:
    branches:
      - main
      - beta

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get version and commit
        run: |
          BASE_VERSION=$(grep '^SCRIPT_BASE_VERSION=' config_wg.sh | head -n1 | cut -d'"' -f2)
          CHANNEL=$(grep '^SCRIPT_CHANNEL=' config_wg.sh | head -n1 | cut -d'"' -f2)
          COMMIT=$(git rev-parse --short HEAD)
          [[ -z "$BASE_VERSION" ]] && BASE_VERSION="1.0.0"
          [[ -z "$CHANNEL" ]] && CHANNEL="stable"
          echo "${BASE_VERSION}-${CHANNEL}-${COMMIT}" > version.txt

      - name: Commit and push version.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add version.txt
          git commit -m "Mise à jour version.txt [auto]" || exit 0
          git push "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" HEAD:${GITHUB_REF#refs/heads/}